### PR TITLE
Delete .github/workflows/c-cpp.yml

### PR DESCRIPTION
**Pull request by eeshvardasikcm-workflow**

### CODE REVIEW

**Review by eeshvardasikcm — APPROVED** [review]

**Review by eeshvardasikcm — APPROVED** [review]

**Comment by eeshvardasikcm-workflow** [comment]
what happens if i add some c++ code? will that allow one person to approve multiple times? I don't think so. I will probably have to add another reviewing mechanism.

**Comment by eeshvardasikcm** [comment]
> what happens if i add some c++ code? will that allow one person to approve multiple times? I don't think so. I will probably have to add another reviewing mechanism.

🟣 question 🟣

**Review by eeshvardasikcm — DISMISSED** [review]
this code maybe won't work.

**Comment by eeshvardasikcm** [comment]
> > what happens if i add some c++ code? will that allow one person to approve multiple times? I don't think so. I will probably have to add another reviewing mechanism.
> 
> 🟣 question 🟣

did not make a difference

**Review by eeshvardasikcm — APPROVED** [review]

**Comment by eeshvardasikcm** [comment]
Workflow cpp 6 #8 now has these same changes

**Pull request closed without merging**
